### ISSUE TITLE
Role based whitelists for non-existing ks/table doesn't work

### ISSUE THREAD

**Issue by eperott** [Ericsson/ecaudit#10]
While it is possible to whitelist a non-existing table, there will still be entries in the audit log if a client attempt to access that non-existing table.

For instance, this shows in the integration tests if we upgrade java-driver version to 3.6.0.

```
org.apache.cassandra.exceptions.InvalidRequestException: unconfigured table peers_v2
	at org.apache.cassandra.thrift.ThriftValidation.validateColumnFamilyWithCompactMode(ThriftValidation.java:119) ~[cassandra-all-3.0.16.jar:3.0.16]
	at org.apache.cassandra.cql3.statements.SelectStatement$RawStatement.prepare(SelectStatement.java:897) ~[cassandra-all-3.0.16.jar:3.0.16]
	at org.apache.cassandra.cql3.statements.SelectStatement$RawStatement.prepare(SelectStatement.java:892) ~[cassandra-all-3.0.16.jar:3.0.16]
	at org.apache.cassandra.cql3.QueryProcessor.getStatement(QueryProcessor.java:520) ~[cassandra-all-3.0.16.jar:3.0.16]
	at com.ericsson.bss.cassandra.ecaudit.AuditEntryBuilderFactory.createEntryBuilder(AuditEntryBuilderFactory.java:76) ~[classes/:na]
	at com.ericsson.bss.cassandra.ecaudit.AuditAdapter.auditRegular(AuditAdapter.java:83) [classes/:na]
	at com.ericsson.bss.cassandra.ecaudit.handler.AuditQueryHandler.process(AuditQueryHandler.java:98) [classes/:na]
	at org.apache.cassandra.transport.messages.QueryMessage.execute(QueryMessage.java:115) [cassandra-all-3.0.16.jar:3.0.16]
	at org.apache.cassandra.transport.Message$Dispatcher.channelRead0(Message.java:513) [cassandra-all-3.0.16.jar:3.0.16]
	at org.apache.cassandra.transport.Message$Dispatcher.channelRead0(Message.java:407) [cassandra-all-3.0.16.jar:3.0.16]
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105) [netty-all-4.0.44.Final.jar:4.0.44.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:357) [netty-all-4.0.44.Final.jar:4.0.44.Final]
	at io.netty.channel.AbstractChannelHandlerContext.access$600(AbstractChannelHandlerContext.java:35) [netty-all-4.0.44.Final.jar:4.0.44.Final]
	at io.netty.channel.AbstractChannelHandlerContext$7.run(AbstractChannelHandlerContext.java:348) [netty-all-4.0.44.Final.jar:4.0.44.Final]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [na:1.8.0_181]
	at org.apache.cassandra.concurrent.AbstractLocalAwareExecutorService$FutureTask.run(AbstractLocalAwareExecutorService.java:164) [cassandra-all-3.0.16.jar:3.0.16]
	at org.apache.cassandra.concurrent.SEPWorker.run(SEPWorker.java:105) [cassandra-all-3.0.16.jar:3.0.16]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_181]
```

**Comment by tobier** [comment]
Does this apply to both role-based whitelists and file-based whitelist?

**Comment by eperott** [comment]
Have not verified, but I'm guessing this only impacts how role based whitelists work, since the yaml-filter will filter on user level only.

**Comment by tobier** [comment]
You're right, my bad.
From the stracktrace it looks like we're auditing before processing the query? Or are we using the QueryProcessor to to whitelist validation?

**Comment by eperott** [comment]
This stack trace is for a non-prepared statement. Haven't verified, but this is probably only relevant for non-prepared statements.

When we get a non-prepared statement, we use the QueryProcessor to resolve (or prepare) the statement "manually". This happens before the QueryProcessor does the actual processing of the query.
