### ISSUE TITLE
Backport ecAudit to 2.2.x

### ISSUE THREAD

**Issue by eperott** [Ericsson/ecaudit#111]
Potential users have requested a backport of ecAudit that would be compatible with Cassandra 2.2.8. We should investigate if this is possible, with our without compromises in supported features.

Ideally we should have the very same features on all flavors of ecAudit, if nothing else for sake of maintainability.

Also, since 2.2.8 is a rather old release of the 2.2.x series, we should aim to start with a backport to 2.2.14 (latest at the time of writing). If necessary we'd make a backport further to 2.2.8 if necessary.

**Comment by eperott** [comment]
First limitation while looking into backporting ecAudit to 2.2.14:
* The client peer IP address will not be present in audit records created during authentication.

**Comment by eperott** [comment]
It may be possible to overcome the string literal formatting issue to make logs appear identical with other flavors of ecAudit. At least this should be possible for the most common types such as UTF8 strings.

There are some challenges to get a clean run of the integration tests. There is a little bit of a dependency hell w.r.t ecAudit <-> Cassandra <-> Client Driver <-> Guava. This needs more work

**Comment by eperott** [comment]
Work in progress is here:
https://github.com/eperott/ecaudit/tree/dev-2.2.14

Open tasks:
* Integration tests run mostly OK, but there are some annoying error messages when shutting down the embedded daemon.
* There is a bunch of hacky solutions in the code to make things run clean in tests. Should get a proper design - for instance the formatting/escaping of literals in prepared statements.
* Review documentation and make adoptions for the new v.2.2.x flavor of ecAudit.
* Run some performance tests.
* Full review.
* Before merging we should create proper target release branch in Ericsson repo.

**Comment by etedpet** [comment]
One issue with the Chronicle logger discovered:
Since the Client IP address is not available during authentication, there is issue when writing/reading that "field" to/from the chronicle binary. There must be a way to know if the field is written the binary record or not.

The stacktrace from ecLog when failing to read a auth log entry:
Exception in thread "main" java.lang.UnsupportedOperationException: Unknown_0x0
	at net.openhft.chronicle.wire.BinaryWire$BinaryValueIn.cantRead(BinaryWire.java:3487)
	at net.openhft.chronicle.wire.BinaryWire$BinaryValueIn.bytes(BinaryWire.java:2435)
	at com.ericsson.bss.cassandra.ecaudit.common.chronicle.AuditRecordReadMarshallable.readInetSocketAddress(AuditRecordReadMarshallable.java:91)
	at com.ericsson.bss.cassandra.ecaudit.common.chronicle.AuditRecordReadMarshallable.readMarshallable(AuditRecordReadMarshallable.java:52)
	at net.openhft.chronicle.queue.impl.single.SingleChronicleQueueExcerpts$StoreTailer.readDocument(SingleChronicleQueueExcerpts.java:1072)
	at com.ericsson.bss.cassandra.ecaudit.eclog.QueueReader.readNext(QueueReader.java:101)
	at com.ericsson.bss.cassandra.ecaudit.eclog.QueueReader.maybeReadNext(QueueReader.java:94)
	at com.ericsson.bss.cassandra.ecaudit.eclog.QueueReader.hasRecordAvailable(QueueReader.java:86)
	at com.ericsson.bss.cassandra.ecaudit.eclog.LogPrinter.isEligibleForPrint(LogPrinter.java:107)
	at com.ericsson.bss.cassandra.ecaudit.eclog.LogPrinter.print(LogPrinter.java:49)
	at com.ericsson.bss.cassandra.ecaudit.eclog.EcLog.main(EcLog.java:42)

This issue would be solved by the #102 issue. So this issue should be resolved before continuing with this issue.

This was not discovered in IntegrationTest (ITVerifyChronicleBackend.java) since it was refactored in #107. An extra test case should be added to cover the authentication logging in chronicle.

**Comment by etedpet** [comment]
Cassandra 2.2.x runs on java7, but ecAudit will require java8!
This is probably not an practical issue, but we should state that somewhere in the documentation.

**Comment by laxmikant99** [comment]
> Cassandra 2.2.x runs on java7, but ecAudit will require java8!
> This is probably not an practical issue, but we should state that somewhere in the documentation.

+1

**Comment by etedpet** [comment]
Ran a performance test (run_ccm_performance_test.sh) on C2.2.14 and it looks as expected (similar to C3.*).
![ecAudit-performace_2 2 14](https://user-images.githubusercontent.com/12560457/63923485-f0eb8880-ca46-11e9-8ad8-2edaae182dd3.png)

**Comment by etedpet** [comment]
[ecaudit-performance_2.2.14.html.zip](https://github.com/Ericsson/ecaudit/files/3554564/ecaudit-performance_2.2.14.html.zip)

**Comment by etedpet** [comment]
Closed by pull request #116
