### ISSUE TITLE
Schema version mismatch detected in Kubernetes Cluster

### ISSUE THREAD

**Issue by pushpendra-rajpoot** [Ericsson/ecaudit#168]
Hi ecAudit Team,

We are using Cassandra 3.11.9 and ecAduit 2.6.0 with Role based whitelist. We are deploying cassandra in Kubernetes cluster and in 'docker-entrypoint' script on pod-1, when we alter 'system_auth' replication factor to 2 using 'cassandra' super user then we got below error:

`<stdin>:1:Warning: schema version mismatch detected; check the schema versions of your nodes in system.local and system.peers.
<stdin>:1:Schema metadata was not refreshed. See log for details.
Connection error: ('Unable to connect to any servers', {'192.168.131.17': AuthenticationFailed('Failed to authenticate to 192.
168.131.17: Error from server: code=0100 [Bad credentials] message="Provided username admin and/or password are incorrect"',)})`

If we deploy Cassandra without ecAudit, then it works fine.

Based on our analysis, we found that when we altered 'system_auth' keyspace replication factor, ecAudit tried to audit this record and goes to find the whitelist user for this alter statement (Though ecAudit cached these roles but still it hits database). This is where it's not able to get the whitelist role using 'cassandra' super user as it tried with CL.QUORUM for 'cassandra' user but only pod-0 is up when docker-entrypoint executes on pod-1.

So, what we thought if there is an exception when getting whitelist user, we will not audit a record when there is an exception while fetching whitelist roles from database.

**Comment by eperott** [comment]
Thanks for the report.

Had a look at your patch and found references to #57 in the relevant code path. Have to admit, when we talked about this off-line I had totally forgot about that ticket. Looking at the patch for #57, it looks like it should fixe the issue you're observing. But clearly it's not.

You're proposed solution may be a simpler and more robust way to deal with this. But this also renders a fair bit of code useles (originally introduced to fix #57). So, if we're going with your patch, then we should clean up some things I think.

A couple of questions w.r.t your patch.
* Does it resolve your issue fully?
* Could you provide some more details of the underlying issue. For instance, what does the stacktrace look like if you add a log line to the new catch block you introduced in proposed patch.

**Comment by eperott** [comment]
When looking at fix for #57, would it resolve your case to modify things in WhitelistDataAccess a bit so that we're waiting for schema agreement even if we don't create the table?

**Comment by pushpendra-rajpoot** [comment]
This patch works for me. 

I added stack trace and tried to built jar. But existing PMS rules do not allow it so I removed it and tested this patch without stack trace. I think I can build a jar by disabling PMD rules but I did not try it after disabling PMD rules.

**Comment by pushpendra-rajpoot** [comment]
Hereunder is the stack trace:

`ERROR [Native-Transport-Requests-1] 2021-04-18 08:01:44,254 DefaultAuditor.java:87 - cannot fetch whitelist role, **cause**=null, **message**=Cannot achieve consistency level QUORUM
ERROR [Native-Transport-Requests-1] 2021-04-18 08:01:44,257 Message.java:833 - Unexpected exception during request; channel = [id: 0x97e330da, L:/127.0.0.1:9042 - R:/127.0.0.1:52102]
java.lang.StackOverflowError: null
        at java.lang.reflect.InvocationTargetException.<init>(InvocationTargetException.java:72) ~[na:1.8.0_282]
        at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source) ~[na:na]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_282]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_282]
        at ch.qos.logback.classic.spi.ThrowableProxy.<init>(ThrowableProxy.java:69) ~[logback-classic-1.1.3.jar:na]
        at ch.qos.logback.classic.spi.ThrowableProxy.<init>(ThrowableProxy.java:61) ~[logback-classic-1.1.3.jar:na]
        at ch.qos.logback.classic.spi.ThrowableProxy.<init>(ThrowableProxy.java:75) ~[logback-classic-1.1.3.jar:na]
...............
...............
        at ch.qos.logback.classic.spi.LoggingEvent.<init>(LoggingEvent.java:121) ~[logback-classic-1.1.3.jar:na]
        at ch.qos.logback.classic.Logger.buildLoggingEventAndAppend(Logger.java:440) ~[logback-classic-1.1.3.jar:na]
        at ch.qos.logback.classic.Logger.filterAndLog_0_Or3Plus(Logger.java:396) ~[logback-classic-1.1.3.jar:na]
        at ch.qos.logback.classic.Logger.error(Logger.java:559) ~[logback-classic-1.1.3.jar:na]
        at com.ericsson.bss.cassandra.ecaudit.facade.DefaultAuditor.shouldAudit(DefaultAuditor.java:88) ~[ecaudit.jar:na]
        at com.ericsson.bss.cassandra.ecaudit.facade.DefaultAuditor.audit(DefaultAuditor.java:72) ~[ecaudit.jar:na]
        at com.ericsson.bss.cassandra.ecaudit.AuditAdapter.auditAuth(AuditAdapter.java:216) ~[ecaudit.jar:na]
        at com.ericsson.bss.cassandra.ecaudit.AuditAdapter.auditAuth(AuditAdapter.java:187) ~[ecaudit.jar:na]
        at com.ericsson.bss.cassandra.ecaudit.auth.AuditAuthenticator$AuditSaslNegotiator.auditAuth(AuditAuthenticator.java:180) ~[ecaudit.jar:na]
        at com.ericsson.bss.cassandra.ecaudit.auth.AuditAuthenticator$AuditSaslNegotiator.getAuthenticatedUser(AuditAuthenticator.java:166) ~[ecaudit.jar:na]
        at org.apache.cassandra.transport.messages.AuthResponse.execute(AuthResponse.java:79) ~[apache-cassandra-3.11.9-E003.jar:3.11.9-E003]
        at org.apache.cassandra.transport.Message$Dispatcher.processRequest(Message.java:686) [apache-cassandra-3.11.9-E003.jar:3.11.9-E003]
        at org.apache.cassandra.transport.Message$Dispatcher.lambda$channelRead0$0(Message.java:592) [apache-cassandra-3.11.9-E003.jar:3.11.9-E003]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[na:1.8.0_282]
        at org.apache.cassandra.concurrent.AbstractLocalAwareExecutorService$FutureTask.run(AbstractLocalAwareExecutorService.java:162) ~[apache-cassandra-3.11.9-E003.jar:3.11.9-E003]
        at org.apache.cassandra.concurrent.SEPWorker.run(SEPWorker.java:113) ~[apache-cassandra-3.11.9-E003.jar:3.11.9-E003]
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[netty-all-4.1.42.Final.jar:4.1.42.Final]
        at java.lang.Thread.run(Thread.java:748) ~[na:1.8.0_282]
`

**Comment by eperott** [comment]
Thanks.

That looks a bit strange thought. Do you think this is representing original exception in that catch block?

**Comment by pushpendra-rajpoot** [comment]
I got previous error when I set 'log_timing_strategy=post_logging'.

Below error is of 'pre_logging' strategy:

`{"version":"0.3.0","timestamp":"2021-04-19T04:10:06.536Z","severity":"trace","service_id":"eric-data-wide-column-database-cd","message":"[org.apache.cassandra.transport.Message] Received: QUERY SELECT schema_version FROM system.local WHERE key='local'[pageSize = -1], v=4/v4"}
{"version":"0.3.0","timestamp":"2021-04-19T04:10:06.537Z","severity":"trace","service_id":"eric-data-wide-column-database-cd","message":"[org.apache.cassandra.db.ConsistencyLevel] Live nodes [/192.168.49.48] do not satisfy ConsistencyLevel (2 required)"}
{"version":"0.3.0","timestamp":"2021-04-19T04:10:06.537Z","severity":"error","service_id":"eric-data-wide-column-database-cd","message":"[com.ericsson.bss.cassandra.ecaudit.facade.DefaultAuditor] cannot fetch whitelist role, cause=null, message=Cannot achieve consistency level QUORUM"}
{"version":"0.3.0","timestamp":"2021-04-19T04:10:06.538Z","severity":"trace","service_id":"eric-data-wide-column-database-cd","message":"[org.apache.cassandra.tracing.Tracing] request complete"}
{"version":"0.3.0","timestamp":"2021-04-19T04:10:06.540Z","severity":"error","service_id":"eric-data-wide-column-database-cd","message":"[org.apache.cassandra.transport.Message] Unexpected exception during request; channel = [id: 0xd9fb1a24, L:/192.168.49.48:9042 - R:/192.168.105.198:41904] java.lang.StackOverflowError: null\n  at java.lang.ReflectiveOperationException.<init>(ReflectiveOperationException.java:89)\n     at java.lang.reflect.InvocationTargetException.<init>(InvocationTargetException.java:72)\n   at sun.reflect.GeneratedMethodAccessor5.invoke(Unknown Source)\n        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)\n   at java.lang.reflect.Method.invoke(Method.java:498)\n   at ch.qos.logback.classic.spi.ThrowableProxy.<init>(ThrowableProxy.java:69)\n        at ch.qos.logback.classic.spi.ThrowableProxy.<init>(ThrowableProxy.java:61)\n        at ch.qos.logback.classic.spi.ThrowableProxy.<init>(ThrowableProxy.java:75)\n   at ch.qos.logback.classic.spi.ThrowableProxy.<init>(ThrowableProxy.java:61)\n        at ch.qos.logback.classic.spi.ThrowableProxy.<init>(ThrowableProxy.java:75)\n        at ch.qos.logback.classic.spi.ThrowableProxy.<init>(ThrowableProxy.java:61)\n   at ch.qos.logback.classic.spi.ThrowableProxy.<init>(ThrowableProxy.java:75)\n        at ch.qos.logback.classic.spi.ThrowableProxy.<init>(ThrowableProxy.java:61)\n 
.................
.................
ThrowableProxy.java:61)\n        at ch.qos.logback.classic.spi.ThrowableProxy.<init>(ThrowableProxy.java:75)\n   at ch.qos.logback.classic.spi.ThrowableProxy.<init>(ThrowableProxy.java:61)\n        at ch.qos.logback.classic.spi.ThrowableProxy.<init>(ThrowableProxy.java:75)\n        at ch.qos.logback.classic.spi.ThrowableProxy.<init>(ThrowableProxy.java:61)\n   at ch.qos.logback.classic.spi.ThrowableProxy.<init>(ThrowableProxy.java:75)\n        at ch.qos.logback.classic.spi.ThrowableProxy.<init>(ThrowableProxy.java:61)\n        at ch.qos.logback.classic.spi.ThrowableProxy.<init>(ThrowableProxy.java:75)\n   at ch.qos.logback.classic.spi.ThrowableProxy.<init>(ThrowableProxy.java:61)\n        at ch.qos.logback.classic.spi.ThrowableProxy.<init>(ThrowableProxy.java:75)\n        at ch.qos.logback.classic.spi.ThrowableProxy.<init>(ThrowableProxy.java:61)\n   at ch.qos.logback.classic.spi.ThrowableProxy.<init>(ThrowableProxy.java:75)\n        at ch.qos.logback.classic.spi.ThrowableProxy.<init>(ThrowableProxy.java:61)\n        at ch.qos.logback.classic.spi.ThrowableProxy.<init>(ThrowableProxy.java:75)\n   at ch.qos.logback.classic.spi.LoggingEvent.<init>(LoggingEvent.java:121)\n   at ch.qos.logback.classic.Logger.buildLoggingEventAndAppend(Logger.java:440)\n       at ch.qos.logback.classic.Logger.filterAndLog_0_Or3Plus(Logger.java:396)\n      at ch.qos.logback.classic.Logger.error(Logger.java:559)\n    at com.ericsson.bss.cassandra.ecaudit.facade.DefaultAuditor.shouldAudit(DefaultAuditor.java:88)\n    at com.ericsson.bss.cassandra.ecaudit.facade.DefaultAuditor.audit(DefaultAuditor.java:72)\n     at com.ericsson.bss.cassandra.ecaudit.AuditAdapter.auditRegular(AuditAdapter.java:107)\n     at com.ericsson.bss.cassandra.ecaudit.handler.AuditQueryHandler.process(AuditQueryHandler.java:108)\n        at org.apache.cassandra.transport.messages.QueryMessage.execute(QueryMessage.java:116)\n     at org.apache.cassandra.transport.Message$Dispatcher.processRequest(Message.java:686)\n at org.apache.cassandra.transport.Message$Dispatcher.lambda$channelRead0$0(Message.java:592)\n       at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)\n at org.apache.cassandra.concurrent.AbstractLocalAwareExecutorService$FutureTask.run(AbstractLocalAwareExecutorService.java:162)\n    at org.apache.cassandra.concurrent.SEPWorker.run(SEPWorker.java:113)\n       at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)\n      at java.lang.Thread.run(Thread.java:748)\n"}
`

Hereunder is my 'try-catch' snippet:

`try {
      return !this.filter.isWhitelisted(logEntry);
    } catch (Exception ex) {
      LOG.error("cannot fetch whitelist role, cause={}, message={}", ex.getCause(), ex.getMessage());
      LOG.error("cannot fetch whitelist role, error=", ex);
      return true;
    }`

**Comment by eperott** [comment]
@pushpendra-rajpoot , the stacktraces you've shared are showing issues with the call to error() itself. Did you find out how to resolve this? Perhaps something related to the other issue I referred to before:
https://github.com/Ericsson/ecaudit/pull/73/files#diff-a51529b157129bbd8ab3eedfa60872753c4d218be9f0c026d3c00993dcf88bb4R52

What I'm really interested to learn is what Exception that was raised in the call to isWhitelisted().

**Comment by pushpendra-rajpoot** [comment]
Hi @eperott, Apology for long wait time.

Hereunder is the stacktrace of exception which is raised in the call to isWhitelisted():

org.apache.cassandra.exceptions.UnavailableException: Cannot achieve consistency level QUORUM
	at org.apache.cassandra.db.ConsistencyLevel.assureSufficientLiveNodes(ConsistencyLevel.java:334)
	at org.apache.cassandra.service.AbstractReadExecutor.getReadExecutor(AbstractReadExecutor.java:162)
	at org.apache.cassandra.service.StorageProxy$SinglePartitionReadLifecycle.<init>(StorageProxy.java:1776)
	at org.apache.cassandra.service.StorageProxy.fetchRows(StorageProxy.java:1738)
	at org.apache.cassandra.service.StorageProxy.readRegular(StorageProxy.java:1681)
	at org.apache.cassandra.service.StorageProxy.read(StorageProxy.java:1596)
	at org.apache.cassandra.db.SinglePartitionReadCommand$Group.execute(SinglePartitionReadCommand.java:1187)
	at org.apache.cassandra.cql3.statements.SelectStatement.execute(SelectStatement.java:315)
	at org.apache.cassandra.cql3.statements.SelectStatement.execute(SelectStatement.java:285)
	at com.ericsson.bss.cassandra.ecaudit.auth.WhitelistDataAccess.getWhitelist(WhitelistDataAccess.java:161)
	at com.ericsson.bss.cassandra.ecaudit.filter.role.RoleAuditFilter.isOperationWhitelistedOnResourceByRole(RoleAuditFilter.java:136)
	at com.ericsson.bss.cassandra.ecaudit.filter.role.RoleAuditFilter.lambda$isOperationWhitelistedOnResourceByRoles$1(RoleAuditFilter.java:131)
	at java.util.stream.MatchOps$1MatchSink.accept(MatchOps.java:90)
	at java.util.HashMap$KeySpliterator.tryAdvance(HashMap.java:1577)
	at java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:126)
	at java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:499)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:486)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472)
	at java.util.stream.MatchOps$MatchOp.evaluateSequential(MatchOps.java:230)
	at java.util.stream.MatchOps$MatchOp.evaluateSequential(MatchOps.java:196)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.anyMatch(ReferencePipeline.java:516)
	at com.ericsson.bss.cassandra.ecaudit.filter.role.RoleAuditFilter.isOperationWhitelistedOnResourceByRoles(RoleAuditFilter.java:131)
	at com.ericsson.bss.cassandra.ecaudit.filter.role.RoleAuditFilter.lambda$isWhitelistedUnchecked$0(RoleAuditFilter.java:119)
	at java.util.stream.MatchOps$1MatchSink.accept(MatchOps.java:90)
	at java.util.Spliterators$IteratorSpliterator.tryAdvance(Spliterators.java:1812)
	at java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:126)
	at java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:499)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:486)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472)
	at java.util.stream.MatchOps$MatchOp.evaluateSequential(MatchOps.java:230)
	at java.util.stream.MatchOps$MatchOp.evaluateSequential(MatchOps.java:196)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.allMatch(ReferencePipeline.java:521)
	at com.ericsson.bss.cassandra.ecaudit.filter.role.RoleAuditFilter.isWhitelistedUnchecked(RoleAuditFilter.java:119)
	at org.apache.cassandra.auth.AuthCache.get(AuthCache.java:104)
	at com.ericsson.bss.cassandra.ecaudit.filter.role.RoleAuditFilterCache.isWhitelisted(RoleAuditFilterCache.java:54)
	at com.ericsson.bss.cassandra.ecaudit.filter.role.RoleAuditFilter.isWhitelisted(RoleAuditFilter.java:100)
	at com.ericsson.bss.cassandra.ecaudit.facade.DefaultAuditor.shouldAudit(DefaultAuditor.java:87)
	at com.ericsson.bss.cassandra.ecaudit.facade.DefaultAuditor.audit(DefaultAuditor.java:73)
	at com.ericsson.bss.cassandra.ecaudit.AuditAdapter.auditRegular(AuditAdapter.java:107)
	at com.ericsson.bss.cassandra.ecaudit.handler.AuditQueryHandler.process(AuditQueryHandler.java:108)
	at org.apache.cassandra.transport.messages.QueryMessage.execute(QueryMessage.java:116)
	at org.apache.cassandra.transport.Message$Dispatcher.processRequest(Message.java:686)
	at org.apache.cassandra.transport.Message$Dispatcher.lambda$channelRead0$0(Message.java:592)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at org.apache.cassandra.concurrent.AbstractLocalAwareExecutorService$FutureTask.run(AbstractLocalAwareExecutorService.java:162)
	at org.apache.cassandra.concurrent.SEPWorker.run(SEPWorker.java:113)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)
	Suppressed: com.google.common.util.concurrent.UncheckedExecutionException: org.apache.cassandra.exceptions.UnavailableException: Cannot achieve consistency level QUORUM
		at com.ericsson.bss.cassandra.ecaudit.filter.role.RoleAuditFilterCache.isWhitelisted(RoleAuditFilterCache.java:60)
		... 13 more
	Caused by: [CIRCULAR REFERENCE: org.apache.cassandra.exceptions.UnavailableException: Cannot achieve consistency level QUORUM]

Also, I am trying the get the more details of this cause and will update if found anything.

**Comment by manmagic3** [comment]
@eperott @pushpendra-rajpoot , we might be hitting this bug https://jira.qos.ch/browse/LOGBACK-1454.

**Comment by pushpendra-rajpoot** [comment]
Hi @manmagic3, we are hitting LOGBACK-1454 bug.

In the 'tryGetCassandraExceptionCause' method of Exceptions class, we are creating a 'cause' from giving exception and then we are adding given exception as suppressed exception in this 'cause'. This is creating a circular reference.

Here is snippet of Exceptions class:
       `LOG.info("inside tryGetCassandraExceptionCause, cause={}", cause);
        if (cause instanceof CassandraException)
        {
            cause.addSuppressed(exception);
            
            LOG.info("inside tryGetCassandraExceptionCause, --IF-- condition");

            cause.printStackTrace();
            
            return (CassandraException) cause;
        }`

Hereunder is the logs of above snippet:

`[com.ericsson.bss.cassandra.ecaudit.utils.Exceptions] inside tryGetCassandraExceptionCause, cause={} org.apache.cassandra.exceptions.UnavailableException: Cannot achieve consistency level QUORUM\n	at org.apache.cassandra.db.ConsistencyLevel.assureSufficientLiveNodes(ConsistencyLevel.java:334)\n	at org.apache.cassandra.service.AbstractReadExecutor.getReadExecutor(AbstractReadExecutor.java:162)\n	at org.apache.cassandra.service.StorageProxy$SinglePartitionReadLifecycle.<init>(StorageProxy.java:1776)\n	at org.apache.cassandra.service.StorageProxy.fetchRows(StorageProxy.java:1738)\n	at org.apache.cassandra.service.StorageProxy.readRegular(StorageProxy.java:1681)\n	at org.apache.cassandra.service.StorageProxy.read(StorageProxy.java:1596)\n	at org.apache.cassandra.db.SinglePartitionReadCommand$Group.execute(SinglePartitionReadCommand.java:1187)\n	at org.apache.cassandra.cql3.statements.SelectStatement.execute(SelectStatement.java:315)\n	at org.apache.cassandra.cql3.statements.SelectStatement.execute(SelectStatement.java:285)\n	at com.ericsson.bss.cassandra.ecaudit.auth.WhitelistDataAccess.getWhitelist(WhitelistDataAccess.java:161)\n	at com.ericsson.bss.cassandra.ecaudit.filter.role.RoleAuditFilter.isOperationWhitelistedOnResourceByRole(RoleAuditFilter.java:136)\n	at com.ericsson.bss.cassandra.ecaudit.filter.role.RoleAuditFilter.lambda$isOperationWhitelistedOnResourceByRoles$1(RoleAuditFilter.java:131)\n	at java.util.stream.MatchOps$1MatchSink.accept(MatchOps.java:90)\n	at java.util.HashMap$KeySpliterator.tryAdvance(HashMap.java:1577)\n	at java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:126)\n	at java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:499)\n	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:486)\n	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472)\n	at java.util.stream.MatchOps$MatchOp.evaluateSequential(MatchOps.java:230)\n	at java.util.stream.MatchOps$MatchOp.evaluateSequential(MatchOps.java:196)\n	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)\n	at java.util.stream.ReferencePipeline.anyMatch(ReferencePipeline.java:516)\n	at com.ericsson.bss.cassandra.ecaudit.filter.role.RoleAuditFilter.isOperationWhitelistedOnResourceByRoles(RoleAuditFilter.java:131)\n	at com.ericsson.bss.cassandra.ecaudit.filter.role.RoleAuditFilter.lambda$isWhitelistedUnchecked$0(RoleAuditFilter.java:119)\n	at java.util.stream.MatchOps$1MatchSink.accept(MatchOps.java:90)\n	at java.util.Spliterators$IteratorSpliterator.tryAdvance(Spliterators.java:1812)\n	at java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:126)\n	at java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:499)\n	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:486)\n	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472)\n	at java.util.stream.MatchOps$MatchOp.evaluateSequential(MatchOps.java:230)\n	at java.util.stream.MatchOps$MatchOp.evaluateSequential(MatchOps.java:196)\n	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)\n	at java.util.stream.ReferencePipeline.allMatch(ReferencePipeline.java:521)\n	at com.ericsson.bss.cassandra.ecaudit.filter.role.RoleAuditFilter.isWhitelistedUnchecked(RoleAuditFilter.java:119)\n	at org.apache.cassandra.auth.AuthCache.get(AuthCache.java:104)\n	at com.ericsson.bss.cassandra.ecaudit.filter.role.RoleAuditFilterCache.isWhitelisted(RoleAuditFilterCache.java:54)\n	at com.ericsson.bss.cassandra.ecaudit.filter.role.RoleAuditFilter.isWhitelisted(RoleAuditFilter.java:100)\n	at com.ericsson.bss.cassandra.ecaudit.facade.DefaultAuditor.shouldAudit(DefaultAuditor.java:85)\n	at com.ericsson.bss.cassandra.ecaudit.facade.DefaultAuditor.audit(DefaultAuditor.java:73)\n	at com.ericsson.bss.cassandra.ecaudit.AuditAdapter.auditRegular(AuditAdapter.java:107)\n	at com.ericsson.bss.cassandra.ecaudit.handler.AuditQueryHandler.process(AuditQueryHandler.java:108)\n	at org.apache.cassandra.transport.messages.QueryMessage.execute(QueryMessage.java:116)\n	at org.apache.cassandra.transport.Message$Dispatcher.processRequest(Message.java:686)\n	at org.apache.cassandra.transport.Message$Dispatcher.lambda$channelRead0$0(Message.java:592)\n	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)\n	at org.apache.cassandra.concurrent.AbstractLocalAwareExecutorService$FutureTask.run(AbstractLocalAwareExecutorService.java:162)\n	at org.apache.cassandra.concurrent.SEPWorker.run(SEPWorker.java:113)\n	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)\n	at java.lang.Thread.run(Thread.java:748)\n"}
{"version":"0.3.0","timestamp":"2021-05-25T03:51:42.610Z","severity":"info","service_id":"eric-data-wide-column-database-cd","message":"[com.ericsson.bss.cassandra.ecaudit.utils.Exceptions] inside tryGetCassandraExceptionCause, --IF-- condition"}
org.apache.cassandra.exceptions.UnavailableException: Cannot achieve consistency level QUORUM
	at org.apache.cassandra.db.ConsistencyLevel.assureSufficientLiveNodes(ConsistencyLevel.java:334)
	at org.apache.cassandra.service.AbstractReadExecutor.getReadExecutor(AbstractReadExecutor.java:162)
	at org.apache.cassandra.service.StorageProxy$SinglePartitionReadLifecycle.<init>(StorageProxy.java:1776)
	at org.apache.cassandra.service.StorageProxy.fetchRows(StorageProxy.java:1738)
	at org.apache.cassandra.service.StorageProxy.readRegular(StorageProxy.java:1681)
	at org.apache.cassandra.service.StorageProxy.read(StorageProxy.java:1596)
	at org.apache.cassandra.db.SinglePartitionReadCommand$Group.execute(SinglePartitionReadCommand.java:1187)
	at org.apache.cassandra.cql3.statements.SelectStatement.execute(SelectStatement.java:315)
	at org.apache.cassandra.cql3.statements.SelectStatement.execute(SelectStatement.java:285)
	at com.ericsson.bss.cassandra.ecaudit.auth.WhitelistDataAccess.getWhitelist(WhitelistDataAccess.java:161)
	at com.ericsson.bss.cassandra.ecaudit.filter.role.RoleAuditFilter.isOperationWhitelistedOnResourceByRole(RoleAuditFilter.java:136)
	at com.ericsson.bss.cassandra.ecaudit.filter.role.RoleAuditFilter.lambda$isOperationWhitelistedOnResourceByRoles$1(RoleAuditFilter.java:131)
	at java.util.stream.MatchOps$1MatchSink.accept(MatchOps.java:90)
	at java.util.HashMap$KeySpliterator.tryAdvance(HashMap.java:1577)
	at java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:126)
	at java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:499)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:486)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472)
	at java.util.stream.MatchOps$MatchOp.evaluateSequential(MatchOps.java:230)
	at java.util.stream.MatchOps$MatchOp.evaluateSequential(MatchOps.java:196)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.anyMatch(ReferencePipeline.java:516)
	at com.ericsson.bss.cassandra.ecaudit.filter.role.RoleAuditFilter.isOperationWhitelistedOnResourceByRoles(RoleAuditFilter.java:131)
	at com.ericsson.bss.cassandra.ecaudit.filter.role.RoleAuditFilter.lambda$isWhitelistedUnchecked$0(RoleAuditFilter.java:119)
	at java.util.stream.MatchOps$1MatchSink.accept(MatchOps.java:90)
	at java.util.Spliterators$IteratorSpliterator.tryAdvance(Spliterators.java:1812)
	at java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:126)
	at java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:499)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:486)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472)
	at java.util.stream.MatchOps$MatchOp.evaluateSequential(MatchOps.java:230)
	at java.util.stream.MatchOps$MatchOp.evaluateSequential(MatchOps.java:196)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.allMatch(ReferencePipeline.java:521)
	at com.ericsson.bss.cassandra.ecaudit.filter.role.RoleAuditFilter.isWhitelistedUnchecked(RoleAuditFilter.java:119)
	at org.apache.cassandra.auth.AuthCache.get(AuthCache.java:104)
	at com.ericsson.bss.cassandra.ecaudit.filter.role.RoleAuditFilterCache.isWhitelisted(RoleAuditFilterCache.java:54)
	at com.ericsson.bss.cassandra.ecaudit.filter.role.RoleAuditFilter.isWhitelisted(RoleAuditFilter.java:100)
	at com.ericsson.bss.cassandra.ecaudit.facade.DefaultAuditor.shouldAudit(DefaultAuditor.java:85)
	at com.ericsson.bss.cassandra.ecaudit.facade.DefaultAuditor.audit(DefaultAuditor.java:73)
	at com.ericsson.bss.cassandra.ecaudit.AuditAdapter.auditRegular(AuditAdapter.java:107)
	at com.ericsson.bss.cassandra.ecaudit.handler.AuditQueryHandler.process(AuditQueryHandler.java:108)
	at org.apache.cassandra.transport.messages.QueryMessage.execute(QueryMessage.java:116)
	at org.apache.cassandra.transport.Message$Dispatcher.processRequest(Message.java:686)
	at org.apache.cassandra.transport.Message$Dispatcher.lambda$channelRead0$0(Message.java:592)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at org.apache.cassandra.concurrent.AbstractLocalAwareExecutorService$FutureTask.run(AbstractLocalAwareExecutorService.java:162)
	at org.apache.cassandra.concurrent.SEPWorker.run(SEPWorker.java:113)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)
	Suppressed: com.google.common.util.concurrent.UncheckedExecutionException: org.apache.cassandra.exceptions.UnavailableException: Cannot achieve consistency level QUORUM
		at com.ericsson.bss.cassandra.ecaudit.filter.role.RoleAuditFilterCache.isWhitelisted(RoleAuditFilterCache.java:60)
		... 13 more
	Caused by: [CIRCULAR REFERENCE: org.apache.cassandra.exceptions.UnavailableException: Cannot achieve consistency level QUORUM]`
