### ISSUE TITLE
Error when enabling ecAudit in live system

### ISSUE THREAD

**Issue by eperott** [Ericsson/ecaudit#57]
In the scenario where ecAudit is enabled in a live system by restarting one Cassandra node at a time, requests will fail temporarily. The error is manifesting itself as several rejected requests with AuthenticationException at the client side. This goes on for ~10 seconds just after the first Cassandra node is restarted. After this, traffic will work as expected. Subsequent Cassandra node restarts will not cause any issues. The issue was observed in a multi DC cluster.

The following stack trace is collected from failing node:

```
2019-01-25T11:45:38.760+0100 [SharedPool-Worker-14] ERROR o.a.c.t.Message$UnexpectedChannelExceptionHandler:625 apply Unexpected exception during request; channel = [id: 0x2ee41da4, L:/10.61.186.80:12742 - R:/10.61.186.78:33773]
com.google.common.util.concurrent.UncheckedExecutionException: java.lang.RuntimeException: org.apache.cassandra.exceptions.ReadTimeoutException: Operation timed out - received only 3 responses.
        at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2203) ~[guava-18.0.jar:na]
        at com.google.common.cache.LocalCache.get(LocalCache.java:3937) ~[guava-18.0.jar:na]
        at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:3941) ~[guava-18.0.jar:na]
        at com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:4824) ~[guava-18.0.jar:na]
        at org.apache.cassandra.auth.AuthCache.get(AuthCache.java:108) ~[apache-cassandra-3.0.17-E001.jar:3.0.17-E001]
        at org.apache.cassandra.auth.RolesCache.getRoles(RolesCache.java:44) ~[apache-cassandra-3.0.17-E001.jar:3.0.17-E001]
        at org.apache.cassandra.auth.Roles.getRoles(Roles.java:38) ~[apache-cassandra-3.0.17-E001.jar:3.0.17-E001]
        at com.ericsson.bss.cassandra.ecaudit.filter.role.RoleAuditFilter.isFiltered(RoleAuditFilter.java:46) ~[ecaudit_c3.0-1.0.0.jar:na]
        at com.ericsson.bss.cassandra.ecaudit.filter.yamlandrole.YamlAndRoleAuditFilter.isFiltered(YamlAndRoleAuditFilter.java:48) ~[ecaudit_c3.0-1.0.0.jar:na]
        at com.ericsson.bss.cassandra.ecaudit.facade.DefaultAuditor.audit(DefaultAuditor.java:46) ~[ecaudit_c3.0-1.0.0.jar:na]
        at com.ericsson.bss.cassandra.ecaudit.AuditAdapter.auditAuth(AuditAdapter.java:178) ~[ecaudit_c3.0-1.0.0.jar:na]
        at com.ericsson.bss.cassandra.ecaudit.auth.AuditPasswordAuthenticator$AuditPlainTextSaslAuthenticator.getAuthenticatedUser(AuditPasswordAuthenticator.java:140) ~[ecaudit_c3.0-1.0.0.jar:na]
        at org.apache.cassandra.transport.messages.AuthResponse.execute(AuthResponse.java:78) ~[apache-cassandra-3.0.17-E001.jar:3.0.17-E001]
        at org.apache.cassandra.transport.Message$Dispatcher.channelRead0(Message.java:513) [apache-cassandra-3.0.17-E001.jar:3.0.17-E001]
        at org.apache.cassandra.transport.Message$Dispatcher.channelRead0(Message.java:407) [apache-cassandra-3.0.17-E001.jar:3.0.17-E001]
        at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105) [netty-all-4.0.44.Final.jar:4.0.44.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:357) [netty-all-4.0.44.Final.jar:4.0.44.Final]
        at io.netty.channel.AbstractChannelHandlerContext.access$600(AbstractChannelHandlerContext.java:35) [netty-all-4.0.44.Final.jar:4.0.44.Final]
        at io.netty.channel.AbstractChannelHandlerContext$7.run(AbstractChannelHandlerContext.java:348) [netty-all-4.0.44.Final.jar:4.0.44.Final]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [na:1.8.0_192]
        at org.apache.cassandra.concurrent.AbstractLocalAwareExecutorService$FutureTask.run(AbstractLocalAwareExecutorService.java:164) [apache-cassandra-3.0.17-E001.jar:3.0.17-E001]
        at org.apache.cassandra.concurrent.SEPWorker.run(SEPWorker.java:105) [apache-cassandra-3.0.17-E001.jar:3.0.17-E001]
        at java.lang.Thread.run(Thread.java:748) [na:1.8.0_192]
Caused by: java.lang.RuntimeException: org.apache.cassandra.exceptions.ReadTimeoutException: Operation timed out - received only 3 responses.
        at org.apache.cassandra.auth.CassandraRoleManager.getRole(CassandraRoleManager.java:517) ~[apache-cassandra-3.0.17-E001.jar:3.0.17-E001]
        at org.apache.cassandra.auth.CassandraRoleManager.getRoles(CassandraRoleManager.java:282) ~[apache-cassandra-3.0.17-E001.jar:3.0.17-E001]
        at org.apache.cassandra.auth.RolesCache.lambda$new$0(RolesCache.java:36) ~[apache-cassandra-3.0.17-E001.jar:3.0.17-E001]
        at org.apache.cassandra.auth.AuthCache$1.load(AuthCache.java:183) ~[apache-cassandra-3.0.17-E001.jar:3.0.17-E001]
        at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3527) ~[guava-18.0.jar:na]
        at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2319) ~[guava-18.0.jar:na]
        at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2282) ~[guava-18.0.jar:na]
        at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2197) ~[guava-18.0.jar:na]
        ... 22 common frames omitted
Caused by: org.apache.cassandra.exceptions.ReadTimeoutException: Operation timed out - received only 3 responses.
        at org.apache.cassandra.service.ReadCallback.awaitResults(ReadCallback.java:132) ~[apache-cassandra-3.0.17-E001.jar:3.0.17-E001]
        at org.apache.cassandra.service.ReadCallback.get(ReadCallback.java:137) ~[apache-cassandra-3.0.17-E001.jar:3.0.17-E001]
        at org.apache.cassandra.service.AbstractReadExecutor.get(AbstractReadExecutor.java:145) ~[apache-cassandra-3.0.17-E001.jar:3.0.17-E001]
        at org.apache.cassandra.service.StorageProxy$SinglePartitionReadLifecycle.awaitResultsAndRetryOnDigestMismatch(StorageProxy.java:1716) ~[apache-cassandra-3.0.17-E001.jar:3.0.17-E001]
        at org.apache.cassandra.service.StorageProxy.fetchRows(StorageProxy.java:1665) ~[apache-cassandra-3.0.17-E001.jar:3.0.17-E001]
        at org.apache.cassandra.service.StorageProxy.readRegular(StorageProxy.java:1603) ~[apache-cassandra-3.0.17-E001.jar:3.0.17-E001]
        at org.apache.cassandra.service.StorageProxy.read(StorageProxy.java:1522) ~[apache-cassandra-3.0.17-E001.jar:3.0.17-E001]
        at org.apache.cassandra.db.SinglePartitionReadCommand$Group.execute(SinglePartitionReadCommand.java:1133) ~[apache-cassandra-3.0.17-E001.jar:3.0.17-E001]
        at org.apache.cassandra.cql3.statements.SelectStatement.execute(SelectStatement.java:303) ~[apache-cassandra-3.0.17-E001.jar:3.0.17-E001]
        at org.apache.cassandra.cql3.statements.SelectStatement.execute(SelectStatement.java:264) ~[apache-cassandra-3.0.17-E001.jar:3.0.17-E001]
        at org.apache.cassandra.auth.CassandraRoleManager.getRoleFromTable(CassandraRoleManager.java:525) ~[apache-cassandra-3.0.17-E001.jar:3.0.17-E001]
        at org.apache.cassandra.auth.CassandraRoleManager.getRole(CassandraRoleManager.java:507) ~[apache-cassandra-3.0.17-E001.jar:3.0.17-E001]
        ... 29 common frames omitted
```

**Comment by eperott** [comment]
One way to solve this is to have audit logs off by default. This would allow the plug-in to start-up and create tables before we are trying to pull up whitelist configuration from the role_audit_whitelists table.

Then there's the obvious question, how to enable/disable audit logging. Should we do this with settings in a table usign CQL queries? Or something more elegant?

**Comment by eperott** [comment]
On a second thought, this is probably not related to table-creation at all. In fact, table creation should be completed before the native CQL interface starts to accept connections. The things that are delayed on startup is:
- Table content migration of Cassandra legacy users table to roles table.
- Creation of default super-user
- Table content migration of ecAudit legacy whitelist (but this does not appy to ecAudit v1.0.0 which was used in stack trace above).

Not sure is the delay is related to the error or not though...

An observation about the stack trace is that probably user "cassandra" is used in the request, otherwise the query would be made with CL=LOCAL_ONE. Instead errror indicates that "only" 3 responses were received. If user is "cassandra" then Cassandra has a special case where CL=QUORUM. So a scenario where there are two DCs, where system_auth has RF=3 in each DC, and one DC is totally unreachable, then this error could happen. But if one DC is totally unreachable, then we don't expect a query for user "cassandra" to succeed. Error message could be better though...

**Comment by eperott** [comment]
Can reproduce this by:
- create ccm cluster with 2+2 nodes
- configure NWTopology on system_auth with RF=2+2
- repair system_auth
- execute cassandra_stress with slow steady state
- alter keyspace1 RF=2+2
- ccm node1 stop
- ecaudit/bin/install_into_current_ccm.sh
- ccm node1 start

Will get two different kinds of errors in the log of node1.
This:
```
com.google.common.util.concurrent.UncheckedExecutionException: org.apache.cassandra.exceptions.ReadTimeoutException: Operation timed out - received only 1 responses.
        at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2203) ~[guava-18.0.jar:na]
        at com.google.common.cache.LocalCache.get(LocalCache.java:3937) ~[guava-18.0.jar:na]
        at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:3941) ~[guava-18.0.jar:na]
        at com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:4824) ~[guava-18.0.jar:na]
        at com.ericsson.bss.cassandra.ecaudit.auth.cache.AuthCache.get(AuthCache.java:112) ~[ecaudit_c3.0-2.1.0-SNAPSHOT.jar:na]
        at com.ericsson.bss.cassandra.ecaudit.auth.AuditWhitelistCache.getWhitelist(AuditWhitelistCache.java:70) ~[ecaudit_c3.0-2.1.0-SNAPSHOT.jar:na]
        at com.ericsson.bss.cassandra.ecaudit.filter.role.RoleAuditFilter.isOperationWhitelistedOnResourceByRole(RoleAuditFilter.java:125) ~[ecaudit_c3.0-2.1.0-SNAPSHOT.jar:na]
        at com.ericsson.bss.cassandra.ecaudit.filter.role.RoleAuditFilter.isOperationWhitelistedOnResourceByRoles(RoleAuditFilter.java:114) ~[ecaudit_c3.0-2.1.0-SNAPSHOT.jar:na]
        at com.ericsson.bss.cassandra.ecaudit.filter.role.RoleAuditFilter.isFiltered(RoleAuditFilter.java:88) ~[ecaudit_c3.0-2.1.0-SNAPSHOT.jar:na]
        at com.ericsson.bss.cassandra.ecaudit.filter.role.RoleAuditFilter.isFiltered(RoleAuditFilter.java:79) ~[ecaudit_c3.0-2.1.0-SNAPSHOT.jar:na]
        at com.ericsson.bss.cassandra.ecaudit.facade.DefaultAuditor.audit(DefaultAuditor.java:51) ~[ecaudit_c3.0-2.1.0-SNAPSHOT.jar:na]
        at com.ericsson.bss.cassandra.ecaudit.AuditAdapter.auditAuth(AuditAdapter.java:188) ~[ecaudit_c3.0-2.1.0-SNAPSHOT.jar:na]
        at com.ericsson.bss.cassandra.ecaudit.auth.AuditPasswordAuthenticator$AuditPlainTextSaslAuthenticator.getAuthenticatedUser(AuditPasswordAuthenticator.java:132) ~[ecaudit_c3.0-2.1.0-SNAPSHOT.jar:na]
        at org.apache.cassandra.transport.messages.AuthResponse.execute(AuthResponse.java:78) ~[apache-cassandra-3.0.18.jar:3.0.18]
        at org.apache.cassandra.transport.Message$Dispatcher.channelRead0(Message.java:562) [apache-cassandra-3.0.18.jar:3.0.18]
        at org.apache.cassandra.transport.Message$Dispatcher.channelRead0(Message.java:407) [apache-cassandra-3.0.18.jar:3.0.18]
        at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105) [netty-all-4.0.44.Final.jar:4.0.44.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:357) [netty-all-4.0.44.Final.jar:4.0.44.Final]
        at io.netty.channel.AbstractChannelHandlerContext.access$600(AbstractChannelHandlerContext.java:35) [netty-all-4.0.44.Final.jar:4.0.44.Final]
        at io.netty.channel.AbstractChannelHandlerContext$7.run(AbstractChannelHandlerContext.java:348) [netty-all-4.0.44.Final.jar:4.0.44.Final]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [na:1.8.0_181]
        at org.apache.cassandra.concurrent.AbstractLocalAwareExecutorService$FutureTask.run(AbstractLocalAwareExecutorService.java:164) [apache-cassandra-3.0.18.jar:3.0.18]
        at org.apache.cassandra.concurrent.SEPWorker.run(SEPWorker.java:110) [apache-cassandra-3.0.18.jar:3.0.18]
        at java.lang.Thread.run(Thread.java:748) [na:1.8.0_181]
Caused by: org.apache.cassandra.exceptions.ReadTimeoutException: Operation timed out - received only 1 responses.
        at org.apache.cassandra.service.ReadCallback.awaitResults(ReadCallback.java:132) ~[apache-cassandra-3.0.18.jar:3.0.18]
        at org.apache.cassandra.service.ReadCallback.get(ReadCallback.java:137) ~[apache-cassandra-3.0.18.jar:3.0.18]
        at org.apache.cassandra.service.AbstractReadExecutor.get(AbstractReadExecutor.java:145) ~[apache-cassandra-3.0.18.jar:3.0.18]
        at org.apache.cassandra.service.StorageProxy$SinglePartitionReadLifecycle.awaitResultsAndRetryOnDigestMismatch(StorageProxy.java:1704) ~[apache-cassandra-3.0.18.jar:3.0.18]
        at org.apache.cassandra.service.StorageProxy.fetchRows(StorageProxy.java:1653) ~[apache-cassandra-3.0.18.jar:3.0.18]
        at org.apache.cassandra.service.StorageProxy.readRegular(StorageProxy.java:1591) ~[apache-cassandra-3.0.18.jar:3.0.18]
        at org.apache.cassandra.service.StorageProxy.read(StorageProxy.java:1510) ~[apache-cassandra-3.0.18.jar:3.0.18]
        at org.apache.cassandra.db.SinglePartitionReadCommand$Group.execute(SinglePartitionReadCommand.java:1179) ~[apache-cassandra-3.0.18.jar:3.0.18]
        at org.apache.cassandra.cql3.statements.SelectStatement.execute(SelectStatement.java:303) ~[apache-cassandra-3.0.18.jar:3.0.18]
        at org.apache.cassandra.cql3.statements.SelectStatement.execute(SelectStatement.java:264) ~[apache-cassandra-3.0.18.jar:3.0.18]
        at com.ericsson.bss.cassandra.ecaudit.auth.WhitelistDataAccess.getWhitelist(WhitelistDataAccess.java:140) ~[ecaudit_c3.0-2.1.0-SNAPSHOT.jar:na]
        at com.ericsson.bss.cassandra.ecaudit.auth.cache.AuthCache$1.load(AuthCache.java:187) ~[ecaudit_c3.0-2.1.0-SNAPSHOT.jar:na]
        at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3527) ~[guava-18.0.jar:na]
        at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2319) ~[guava-18.0.jar:na]
        at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2282) ~[guava-18.0.jar:na]
        at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2197) ~[guava-18.0.jar:na]
        ... 23 common frames omitted

```
And this:
```
ERROR [SharedPool-Worker-3] 2019-02-26 14:55:59,302 Message.java:689 - Unexpected exception during request; channel = [id: 0x0e81fc9b, L:/127.0.0.1:9042 - R:/127.0.0.1:39294]
com.google.common.util.concurrent.UncheckedExecutionException: java.lang.RuntimeException: org.apache.cassandra.exceptions.ReadTimeoutException: Operation timed out - received only 2 responses.
        at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2203) ~[guava-18.0.jar:na]
        at com.google.common.cache.LocalCache.get(LocalCache.java:3937) ~[guava-18.0.jar:na]
        at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:3941) ~[guava-18.0.jar:na]
        at com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:4824) ~[guava-18.0.jar:na]
        at org.apache.cassandra.auth.RolesCache.getRoles(RolesCache.java:63) ~[apache-cassandra-3.0.18.jar:3.0.18]
        at org.apache.cassandra.auth.Roles.getRoles(Roles.java:38) ~[apache-cassandra-3.0.18.jar:3.0.18]
        at com.ericsson.bss.cassandra.ecaudit.filter.role.RoleAuditFilter.isFiltered(RoleAuditFilter.java:79) ~[ecaudit_c3.0-2.1.0-SNAPSHOT.jar:na]
        at com.ericsson.bss.cassandra.ecaudit.facade.DefaultAuditor.audit(DefaultAuditor.java:51) ~[ecaudit_c3.0-2.1.0-SNAPSHOT.jar:na]
        at com.ericsson.bss.cassandra.ecaudit.AuditAdapter.auditAuth(AuditAdapter.java:188) ~[ecaudit_c3.0-2.1.0-SNAPSHOT.jar:na]
        at com.ericsson.bss.cassandra.ecaudit.auth.AuditPasswordAuthenticator$AuditPlainTextSaslAuthenticator.getAuthenticatedUser(AuditPasswordAuthenticator.java:132) ~[ecaudit_c3.0-2.1.0-SNAPSHOT.jar:na]
        at org.apache.cassandra.transport.messages.AuthResponse.execute(AuthResponse.java:78) ~[apache-cassandra-3.0.18.jar:3.0.18]
        at org.apache.cassandra.transport.Message$Dispatcher.channelRead0(Message.java:562) [apache-cassandra-3.0.18.jar:3.0.18]
        at org.apache.cassandra.transport.Message$Dispatcher.channelRead0(Message.java:407) [apache-cassandra-3.0.18.jar:3.0.18]
        at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105) [netty-all-4.0.44.Final.jar:4.0.44.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:357) [netty-all-4.0.44.Final.jar:4.0.44.Final]
        at io.netty.channel.AbstractChannelHandlerContext.access$600(AbstractChannelHandlerContext.java:35) [netty-all-4.0.44.Final.jar:4.0.44.Final]
        at io.netty.channel.AbstractChannelHandlerContext$7.run(AbstractChannelHandlerContext.java:348) [netty-all-4.0.44.Final.jar:4.0.44.Final]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [na:1.8.0_181]
        at org.apache.cassandra.concurrent.AbstractLocalAwareExecutorService$FutureTask.run(AbstractLocalAwareExecutorService.java:164) [apache-cassandra-3.0.18.jar:3.0.18]
        at org.apache.cassandra.concurrent.SEPWorker.run(SEPWorker.java:110) [apache-cassandra-3.0.18.jar:3.0.18]
        at java.lang.Thread.run(Thread.java:748) [na:1.8.0_181]
Caused by: java.lang.RuntimeException: org.apache.cassandra.exceptions.ReadTimeoutException: Operation timed out - received only 2 responses.
        at org.apache.cassandra.auth.CassandraRoleManager.getRole(CassandraRoleManager.java:517) ~[apache-cassandra-3.0.18.jar:3.0.18]
        at org.apache.cassandra.auth.CassandraRoleManager.getRoles(CassandraRoleManager.java:282) ~[apache-cassandra-3.0.18.jar:3.0.18]
        at com.ericsson.bss.cassandra.ecaudit.auth.AuditRoleManager.getRoles(AuditRoleManager.java:173) ~[ecaudit_c3.0-2.1.0-SNAPSHOT.jar:na]
        at org.apache.cassandra.auth.RolesCache$1.load(RolesCache.java:115) ~[apache-cassandra-3.0.18.jar:3.0.18]
        at org.apache.cassandra.auth.RolesCache$1.load(RolesCache.java:112) ~[apache-cassandra-3.0.18.jar:3.0.18]
        at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3527) ~[guava-18.0.jar:na]
        at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2319) ~[guava-18.0.jar:na]
        at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2282) ~[guava-18.0.jar:na]
        at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2197) ~[guava-18.0.jar:na]
        ... 20 common frames omitted
Caused by: org.apache.cassandra.exceptions.ReadTimeoutException: Operation timed out - received only 2 responses.
        at org.apache.cassandra.service.ReadCallback.awaitResults(ReadCallback.java:132) ~[apache-cassandra-3.0.18.jar:3.0.18]
        at org.apache.cassandra.service.ReadCallback.get(ReadCallback.java:137) ~[apache-cassandra-3.0.18.jar:3.0.18]
        at org.apache.cassandra.service.AbstractReadExecutor.get(AbstractReadExecutor.java:145) ~[apache-cassandra-3.0.18.jar:3.0.18]
        at org.apache.cassandra.service.StorageProxy$SinglePartitionReadLifecycle.awaitResultsAndRetryOnDigestMismatch(StorageProxy.java:1704) ~[apache-cassandra-3.0.18.jar:3.0.18]
        at org.apache.cassandra.service.StorageProxy.fetchRows(StorageProxy.java:1653) ~[apache-cassandra-3.0.18.jar:3.0.18]
        at org.apache.cassandra.service.StorageProxy.readRegular(StorageProxy.java:1591) ~[apache-cassandra-3.0.18.jar:3.0.18]
        at org.apache.cassandra.service.StorageProxy.read(StorageProxy.java:1510) ~[apache-cassandra-3.0.18.jar:3.0.18]
        at org.apache.cassandra.db.SinglePartitionReadCommand$Group.execute(SinglePartitionReadCommand.java:1179) ~[apache-cassandra-3.0.18.jar:3.0.18]
        at org.apache.cassandra.cql3.statements.SelectStatement.execute(SelectStatement.java:303) ~[apache-cassandra-3.0.18.jar:3.0.18]
        at org.apache.cassandra.cql3.statements.SelectStatement.execute(SelectStatement.java:264) ~[apache-cassandra-3.0.18.jar:3.0.18]
        at org.apache.cassandra.auth.CassandraRoleManager.getRoleFromTable(CassandraRoleManager.java:525) ~[apache-cassandra-3.0.18.jar:3.0.18]
        at org.apache.cassandra.auth.CassandraRoleManager.getRole(CassandraRoleManager.java:507) ~[apache-cassandra-3.0.18.jar:3.0.18]
        ... 28 common frames omitted
```
These stack traces keeps coming for a minute or so.

The other nodes have error messages like this:
```
WARN  [MessagingService-Incoming-/127.0.0.1] 2019-02-26 14:55:49,284 IncomingTcpConnection.java:101 - UnknownColumnFamilyException reading from socket; closing
org.apache.cassandra.db.UnknownColumnFamilyException: Couldn't find table for cfId 0aafeebd-0739-3411-9051-31a04105a825. If a table was just created, this is likely due to the schema not being fully propagated.  Please wait for schema agreement on table creation.
        at org.apache.cassandra.config.CFMetaData$Serializer.deserialize(CFMetaData.java:1495) ~[apache-cassandra-3.0.18.jar:3.0.18]
        at org.apache.cassandra.db.ReadCommand$Serializer.deserialize(ReadCommand.java:660) ~[apache-cassandra-3.0.18.jar:3.0.18]
        at org.apache.cassandra.db.ReadCommand$Serializer.deserialize(ReadCommand.java:599) ~[apache-cassandra-3.0.18.jar:3.0.18]
        at org.apache.cassandra.io.ForwardingVersionedSerializer.deserialize(ForwardingVersionedSerializer.java:50) ~[apache-cassandra-3.0.18.jar:3.0.18]
        at org.apache.cassandra.net.MessageIn.read(MessageIn.java:98) ~[apache-cassandra-3.0.18.jar:3.0.18]
        at org.apache.cassandra.net.IncomingTcpConnection.receiveMessage(IncomingTcpConnection.java:201) ~[apache-cassandra-3.0.18.jar:3.0.18]
        at org.apache.cassandra.net.IncomingTcpConnection.receiveMessages(IncomingTcpConnection.java:178) ~[apache-cassandra-3.0.18.jar:3.0.18]
        at org.apache.cassandra.net.IncomingTcpConnection.run(IncomingTcpConnection.java:92) ~[apache-cassandra-3.0.18.jar:3.0.18]
```

On client-side in cassandra-stress, I get this:
```
ERROR 14:56:05,443 Authentication error on host localhost/127.0.0.1:9042: com.google.common.util.concurrent.UncheckedExecutionException: org.apache.cassandra.exceptions.ReadTimeoutException: Operation timed out - received only 1 responses.
ERROR 14:56:05,452 Authentication error during reconnection to localhost/127.0.0.1:9042, scheduling retry in 2000 milliseconds
com.datastax.driver.core.exceptions.AuthenticationException: Authentication error on host localhost/127.0.0.1:9042: com.google.common.util.concurrent.UncheckedExecutionException: org.apache.cassandra.exceptions.ReadTimeoutException: Operation timed out - received only 1 responses.
	at com.datastax.driver.core.Connection$8.apply(Connection.java:377) ~[cassandra-driver-core-3.0.1-shaded.jar:na]
	at com.datastax.driver.core.Connection$8.apply(Connection.java:347) ~[cassandra-driver-core-3.0.1-shaded.jar:na]
	at com.google.common.util.concurrent.Futures$ChainingListenableFuture.run(Futures.java:906) ~[guava-18.0.jar:na]
	at com.google.common.util.concurrent.Futures$1$1.run(Futures.java:635) ~[guava-18.0.jar:na]
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutorService.execute(MoreExecutors.java:299) ~[guava-18.0.jar:na]
	at com.google.common.util.concurrent.Futures$1.run(Futures.java:632) ~[guava-18.0.jar:na]
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:457) ~[guava-18.0.jar:na]
	at com.google.common.util.concurrent.ExecutionList.executeListener(ExecutionList.java:156) ~[guava-18.0.jar:na]
	at com.google.common.util.concurrent.ExecutionList.execute(ExecutionList.java:145) ~[guava-18.0.jar:na]
	at com.google.common.util.concurrent.AbstractFuture.set(AbstractFuture.java:185) ~[guava-18.0.jar:na]
	at com.datastax.driver.core.Connection$Future.onSet(Connection.java:1182) ~[cassandra-driver-core-3.0.1-shaded.jar:na]
	at com.datastax.driver.core.Connection$Dispatcher.channelRead0(Connection.java:1013) ~[cassandra-driver-core-3.0.1-shaded.jar:na]
	at com.datastax.driver.core.Connection$Dispatcher.channelRead0(Connection.java:936) ~[cassandra-driver-core-3.0.1-shaded.jar:na]
	at com.datastax.shaded.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105) ~[cassandra-driver-core-3.0.1-shaded.jar:na]
	at com.datastax.shaded.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:318) ~[cassandra-driver-core-3.0.1-shaded.jar:na]
	at com.datastax.shaded.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:304) ~[cassandra-driver-core-3.0.1-shaded.jar:na]
	at com.datastax.shaded.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:266) ~[cassandra-driver-core-3.0.1-shaded.jar:na]
	at com.datastax.shaded.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:318) ~[cassandra-driver-core-3.0.1-shaded.jar:na]
	at com.datastax.shaded.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:304) ~[cassandra-driver-core-3.0.1-shaded.jar:na]
	at com.datastax.shaded.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103) ~[cassandra-driver-core-3.0.1-shaded.jar:na]
	at com.datastax.shaded.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:318) ~[cassandra-driver-core-3.0.1-shaded.jar:na]
	at com.datastax.shaded.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:304) ~[cassandra-driver-core-3.0.1-shaded.jar:na]
	at com.datastax.shaded.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:276) ~[cassandra-driver-core-3.0.1-shaded.jar:na]
	at com.datastax.shaded.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:263) ~[cassandra-driver-core-3.0.1-shaded.jar:na]
	at com.datastax.shaded.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:318) ~[cassandra-driver-core-3.0.1-shaded.jar:na]
	at com.datastax.shaded.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:304) ~[cassandra-driver-core-3.0.1-shaded.jar:na]
	at com.datastax.shaded.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:846) ~[cassandra-driver-core-3.0.1-shaded.jar:na]
	at com.datastax.shaded.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:131) ~[cassandra-driver-core-3.0.1-shaded.jar:na]
	at com.datastax.shaded.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:511) ~[cassandra-driver-core-3.0.1-shaded.jar:na]
	at com.datastax.shaded.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:468) ~[cassandra-driver-core-3.0.1-shaded.jar:na]
	at com.datastax.shaded.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:382) ~[cassandra-driver-core-3.0.1-shaded.jar:na]
	at com.datastax.shaded.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:354) ~[cassandra-driver-core-3.0.1-shaded.jar:na]
	at com.datastax.shaded.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:112) ~[cassandra-driver-core-3.0.1-shaded.jar:na]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_181]
```
